(()=>{
const frame=document.getElementById('app');
if(!frame)return;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function route(q){
  const raw=String(q||'').trim();
  if(/보고서|보고자료|협의자료|발주처|자료\s*(?:구성|내용|정리|작성)|어떤\s*내용|무엇을\s*넣|뭘\s*넣|표현.*검토|디자인.*(?:방향|표현)/i.test(raw))return{title:'보고서·협의자료 구성 → 선임 / 책임 / PM에게 먼저',targets:[['사내 · 선임/책임','internal'],['사내 · PM/팀장','internal']],why:'보고자료의 목적, 메시지, 발주처에 보여줄 범위는 기술 협력업체보다 프로젝트 맥락을 아는 사내 상급자가 먼저 판단하는 영역입니다.',together:'구조·설비·소방처럼 특정 기술 내용이 필요할 때만 해당 협력업체에 세부 자료를 요청하세요.'};
  if(/기둥|구조(?:체|설계|변경|안전|검토)?|슬래브|내력벽|철근|보\s*(?:위치|크기|춤|단면|철근|변경)/i.test(raw))return{title:'구조 관련 변경·검토 → 구조설계 협력업체',targets:[['전문분야 · 구조설계 협력업체','pro'],['사내 · 건축 담당자/PM','internal']],why:'기둥·보·슬래브·내력벽 등 구조체 변경은 구조 안전성과 다른 분야 간섭에 직접 영향을 줍니다.',together:'허가도서와 달라지는 변경이면 사내 인허가 담당에게 변경 절차도 함께 확인하세요.'};
  if(/소방|스프링클러|제연|방재|헤드|소방서/i.test(raw)){const admin=/적용|기준|최종|협의|소방서|관할|행정/i.test(raw);return admin?{title:'소방 기준 적용·행정 확인 → 소방설계 + 관할 소방관서',targets:[['전문분야 · 소방설계 협력업체','pro'],['관할기관 · 소방관서','gov']],why:'기술 검토는 소방설계자가 먼저 하고, 관할 협의나 행정 적용 판단은 소방관서 확인이 필요할 수 있습니다.',together:'용도·면적·층수·관련 도면을 함께 준비해 질의하면 답을 받기 쉽습니다.'}:{title:'소방 기술설계 질문 → 소방설계 협력업체',targets:[['전문분야 · 소방설계 협력업체','pro'],['사내 · 건축 담당자','internal']],why:'헤드·제연·배관·방재 등은 기술설계와 건축도면 간 조정이 핵심입니다.',together:'천장고·덕트·전원이 얽히면 기계·전기 담당과도 같이 조정하세요.'};}
  if(/지구단위|도시계획|용도지역|용도지구|용도구역/i.test(raw))return{title:'도시계획 해석 → 사내 검토 후 관할 도시계획 담당',targets:[['사내 · 선임/책임/PM','internal'],['관할기관 · 도시계획 담당부서','gov']],why:'결정도서 해석은 먼저 사내에서 프로젝트 조건과 함께 검토하고, 행정해석이 필요한 부분만 관할 부서에 확인하는 순서가 안전합니다.',together:'토지이음 화면만 보지 말고 최신 결정·변경 고시와 결정도서를 확보하세요.'};
  if(/사업계획승인|사용검사|주택\s*인허가|재개발|재건축/i.test(raw))return{title:'주택사업 인허가 판단 → 사내 주택 인허가/PM + 승인권자',targets:[['사내 · 주택 인허가/PM','internal'],['관할기관 · 승인권자 담당부서','gov']],why:'주택법상 승인·변경·사용검사 경로는 일반 건축허가 절차와 구분해야 합니다.',together:'세대수·면적·배치·부대복리시설 등 무엇이 달라졌는지 비교할 자료를 준비하세요.'};
  if(/건축허가|인허가|변경허가|변경신고|착공신고|사용승인|허가\s*대상|신고\s*대상/i.test(raw))return{title:'인허가 절차 판단 → 사내 인허가 담당/PM부터',targets:[['사내 · 인허가 담당/PM','internal'],['관할기관 · 허가권자 담당부서','gov']],why:'먼저 기존 승인 경로와 변경 내용을 사내에서 정리한 뒤, 공식 판단이 필요한 쟁점만 관할기관에 확인하는 것이 효율적입니다.',together:'기존 허가·승인도서와 변경 비교자료를 같이 준비하세요.'};
  if(/기계|전기|설비|배관|덕트|전력|냉각|통신|공조/i.test(raw))return{title:'기술설계 내용 → 해당 분야 협력업체 + 사내 담당자',targets:[['전문분야 · 해당 설계 협력업체','pro'],['사내 · 건축 담당자/PM','internal']],why:'전문 기술기준과 실제 설계값은 해당 분야 협력업체가 검토하고, 건축과의 우선순위·공간 조정은 사내 담당자가 함께 판단합니다.',together:'질문할 때 최신 평면·단면과 간섭 위치를 같이 보여주세요.'};
  return{title:'업무 판단이 막힘 → 선임 / 책임에게 먼저',targets:[['사내 · 선임/책임','internal'],['사내 · PM/팀장','internal']],why:'질문의 분야가 아직 명확하지 않을 때는 바로 협력업체나 관할기관으로 보내기보다 프로젝트 맥락을 아는 사내 상급자에게 먼저 방향을 확인하는 게 좋습니다.',together:'상급자가 기술·행정 확인이 필요하다고 판단하면 그때 해당 협력업체나 관할기관으로 질문을 구체화하세요.'};
}
function render(d,q){const data=route(q),out=d.getElementById('askAnswer');if(!out)return;const tags=data.targets.map(([label,type])=>`<span class="tag ${type}">${esc(label)}</span>`).join('');out.innerHTML=`<div class="answer-hero"><div class="eyebrow">ROUTING RESULT</div><div class="answer-title">${esc(data.title)}</div><div class="route-tags">${tags}</div></div><div class="answer-grid"><div class="answer-card"><small>WHY</small><p>${esc(data.why)}</p></div><div class="answer-card"><small>TOGETHER</small><p>${esc(data.together)}</p></div></div>`;out.classList.add('show');}
function pinVersion(d){const nodes=[...d.querySelectorAll('.pc150-version,.pc150-mobile-version'),...d.querySelectorAll('.topchip')].filter(x=>x.classList.contains('pc150-version')||x.classList.contains('pc150-mobile-version')||/^v1\./.test(x.textContent.trim()));nodes.forEach(n=>{const next=n.classList.contains('topchip')?'v1.5.3 · 5C FIX':'v1.5.3';if(n.textContent!==next)n.textContent=next;if(!n.dataset.pc153VersionWatch){n.dataset.pc153VersionWatch='1';new MutationObserver(()=>{if(n.textContent!==next)n.textContent=next;}).observe(n,{childList:true,characterData:true,subtree:true});}});}
function install(attempt=0){const d=frame.contentDocument;if(!d||!d.getElementById('pc150Shell')||!d.getElementById('askBtn')){if(attempt<24)setTimeout(()=>install(attempt+1),100);return;}pinVersion(d);const btn=d.getElementById('askBtn');if(!btn.dataset.pc153){btn.dataset.pc153='1';btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const q=d.getElementById('askInput')?.value||'';render(d,q);pinVersion(d);},true);}const input=d.getElementById('askInput');if(input&&!input.dataset.pc153){input.dataset.pc153='1';input.addEventListener('keydown',e=>{if(e.key!=='Enter'||e.shiftKey)return;e.preventDefault();btn.click();});}}
frame.addEventListener('load',()=>install());if(frame.contentDocument?.readyState==='complete')install();
})();