'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const data=new Map([['pc_level','2'],['cc_projects_v1','keep']]);
let blocked=false,writes=0;
const sandbox={window:{},document:{readyState:'loading',body:null,addEventListener(){}},localStorage:{getItem(key){if(blocked)throw Error('denied');return data.get(key)||null},setItem(key,value){if(blocked)throw Error('quota');writes++;data.set(key,value)}}};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('level-store.js','utf8'),sandbox);
const store=sandbox.window.CC_LEVEL_STORE;
assert.equal(store.getItem('pc_level'),'2');
assert.equal(store.setItem('pc_level',3),true);
assert.equal(store.setItem('pc_level',2.5),false);
assert.equal(store.setItem('cc_projects_v1','overwrite'),false);
blocked=true;
assert.equal(store.getItem('pc_level'),null);
assert.equal(store.setItem('pc_level',4),false);
assert.equal(store.getItem('pc_level'),'4','unsaved progress remains in this session');
assert.equal(store.setItem('pc_master_certified','1'),false);
assert.equal(store.getItem('pc_master_certified'),'1');
assert.equal(writes,1);
assert.equal(data.get('cc_projects_v1'),'keep');
assert.equal(data.get('pc_level'),'3','failed save must not alter persisted progress');
console.log('PASS: unavailable/quota storage, session progress, validation and project isolation');
