const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').trim().toLowerCase().replace(/[·ㆍ,./()[\]{}"'`~!@#$%^&*_=+?:;-]/g,'').replace(/\s+/g,'').replace(/(입니다|이에요|예요|이요|요)$/,'');
function actualLevel(){const p=Number(window.CC_LEVEL_STORE.getItem('pc_progress_level'));if(Number.isInteger(p)&&p>=1&&p<=5)return p;const l=Number(window.CC_LEVEL_STORE.getItem('pc_level')||1);return Number.isInteger(l)&&l>=1&&l<=5?l:1}function certified(){return window.CC_LEVEL_STORE.getItem('pc_master_certified')==='1'||window.CC_LEVEL_STORE.getItem('pc_master_unlocked')==='1'||actualLevel()===5}function viewLevel(){if(certified()){const v=Number(window.CC_LEVEL_STORE.getItem('pc_master_preview_level')||5);return Number.isInteger(v)&&v>=1&&v<=5?v:5}return actualLevel()}function setActualLevel(lv){window.CC_LEVEL_STORE.setItem('pc_progress_level',String(lv));window.CC_LEVEL_STORE.setItem('pc_level',String(lv))}
function project(id){return PROJECTS.find(x=>x.id===id)||PROJECTS[1]}
function populate(){TASKS.forEach(t=>$('task').add(new Option(t,t)));const groups=[...new Set(PROJECTS.map(p=>p.group))];groups.forEach(g=>{const og=document.createElement('optgroup');og.label=g;PROJECTS.filter(p=>p.group===g).forEach(p=>og.append(new Option(p.label,p.id)));$('project').append(og)});$('project').value='multi';PHASES.forEach(p=>$('phase').add(new Option(p,p)));}
function updateMasterUI(){document.body.classList.toggle('certified',certified());const lv=viewLevel();document.body.classList.toggle('master-skin',lv===5);$('miniLevel').textContent=(lv===5?'LV.MAX':'LV.'+lv)+' · '+LEVELS[lv].name;const box=$('masterLevels');box.innerHTML='';[1,2,3,4,5].forEach(n=>{const b=document.createElement('button');b.textContent=n===5?'LV.MAX · 건축 마스터':`LV.${n} · ${LEVELS[n].name}`;b.dataset.level=n;b.classList.toggle('active',n===lv);b.onclick=()=>{window.CC_LEVEL_STORE.setItem('pc_master_preview_level',String(n));updateMasterUI();renderLevel();renderQuizOverview();if($('contextResult').children.length)analyze(false);window.CC_RUNTIME.refreshSearchForLevel();if(n===5)showMaster();else hideMaster();};box.append(b)});}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='level')renderLevel();if(name==='quiz')renderQuizOverview();window.scrollTo({top:0,behavior:'smooth'});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){e.preventDefault();showView(b.dataset.view)}});
function phaseIndex(flow,phase){if(!phase||phase==='잘 모르겠습니다')return -1;const key={'사전기획 / 사업검토':['사업','대지','입지','운영'],'기본계획':['규모','기본','대지'],'계획설계':['계획','배치','동선'],'중간설계':['중간'],'실시설계':['실시'],'시공·현장 대응':['공사','시공','착공','시운전']}[phase]||[];let best=-1;flow.some((x,i)=>key.some(k=>x.includes(k))?(best=i,true):false);return best}
function whyData(task){const r=WHY_RULES.find(([re])=>re.test(task));return r?r[1]:{title:'이 업무의 목적은 다음 사람이 판단할 수 있는 상태를 만드는 거예요',why:'결과물 자체보다 프로젝트의 다음 결정·협의·도면 작업이 멈추지 않도록 필요한 정보를 정리하는 데 목적이 있습니다.',risk:'업무 목적을 모르고 형식만 맞추면 자료를 만든 뒤에도 그래서 뭘 결정해야 하지가 남을 수 있습니다.',done:'누가 이 결과물을 보고 무엇을 판단하는지와 다음 행동을 설명할 수 있으면 됩니다.'}}
function projectWhy(p){if(/FAB|공장/.test(p))return '공정·유틸리티 조건이 건축 판단에 일찍 영향을 주는 프로젝트라 업무 목적과 기준을 먼저 맞추는 게 특히 중요합니다.';if(/데이터센터/.test(p))return '전력·냉각 같은 운영 인프라가 건축계획과 강하게 연결되므로 결과물이 어떤 결정을 위한 것인지 먼저 확인합니다.';if(/공항|격납고|운수/.test(p))return '운영조건과 여러 주체의 협의가 건축설계와 함께 움직일 수 있어 자료가 어떤 판단을 위한 것인지 명확히 합니다.';if(/창고|물류/.test(p))return '차량·물류 운영과 건축계획이 함께 움직이므로 단순 도면 작업보다 운영 판단을 같이 봅니다.';if(/공동주택|기숙사|오피스텔/.test(p))return '반복되는 기준이 많아 현재 업무가 어떤 결정과 다음 단계에 연결되는지 놓치지 않는 게 중요합니다.';if(/복합/.test(p))return '여러 용도가 섞이므로 한 업무가 어느 용도·의사결정에 영향을 주는지 구분해서 봅니다.';return '같은 업무도 누가 무엇을 결정하려고 보는지에 따라 필요한 내용과 깊이가 달라집니다.'}
function analyze(navigate=true){const p=project($('project').value),task=$('task').value,phase=$('phase').value,lv=viewLevel(),idx=phaseIndex(p.flow,phase);const nodes=p.flow.map((x,i)=>`${i?'<span class="arrow">→</span>':''}<span class="node ${i===idx?'now':''}">${esc(x)}</span>`).join('');$('contextResult').innerHTML=`<div class="stage-banner"><div class="stage-badge">${idx<0?'?':'NOW'}</div><div class="stage-copy"><small>지금 내가 있는 위치</small><b>${esc(p.label)} · ${phase==='잘 모르겠습니다'?'단계 미상':esc(phase)}</b><p>현재 맡은 업무를 전체 프로젝트 흐름 안에서 먼저 연결합니다.</p></div><div class="stage-task">${esc(task)}</div></div><div class="map"><div class="map-head"><b>이 프로젝트의 큰 그림</b><span>${lv===1?'LV.1 · 설명보다 순서 먼저':'LV.'+lv+' · 필요한 만큼 열기'}</span></div><div class="flow">${nodes}</div><div class="actions"><button data-drawer="context"><small>01 · CONTEXT</small>전후로 어떤 일을 해요?</button><button data-ask-context><small>02 · SEARCH</small>누구에게 물어봐요?</button><button class="warn" data-drawer="caution"><small>03 · CAUTION</small>! 주의할 점</button><button class="${lv<2?'locked':''}" data-drawer="why"><small>04 · ${lv<2?'LOCKED':'WHY'}</small>${lv<2?'왜 이 업무를 해요? 🔒':'왜 이 업무를 해요?'}</button></div><div class="drawer" data-pane="context"><div class="detail-grid"><div class="detail-cell"><small>BEFORE</small><p>${esc(idx>0?p.flow[idx-1]:'프로젝트 시작 전 조건 확인')}</p></div><div class="detail-cell"><small>NOW</small><p>${esc(idx>=0?p.flow[idx]:'현재 단계를 선택하지 않았습니다')} · ${esc(task)}</p></div><div class="detail-cell"><small>NEXT</small><p>${esc(idx>=0&&idx<p.flow.length-1?p.flow[idx+1]:'준공·사용 이후 운영')}</p></div></div></div><div class="drawer caution" data-pane="caution"><b>! 한 가지만 기억</b><br>${esc(p.caution)}</div><div class="drawer why-card" data-pane="why"></div></div>`;const wd=whyData(task);const why=$('contextResult').querySelector('[data-pane="why"]');why.innerHTML=lv<2?'<div class="why-title">LV.2 선임부터 열립니다.</div><p class="lead">승급 퀴즈를 통과하면 업무의 WHY가 열립니다.</p>':`<div class="kicker">LV.2 · WHY</div><div class="why-title">${esc(wd.title)}</div><div class="detail-grid"><div class="detail-cell"><small>WHY</small><p>${esc(wd.why)}</p></div><div class="detail-cell"><small>놓치면</small><p>${esc(wd.risk)}</p></div><div class="detail-cell"><small>DONE</small><p>${esc(wd.done)}</p></div></div><div class="context-note">${esc(projectWhy(p.label))}</div>`;$('contextResult').querySelectorAll('[data-drawer]').forEach(b=>b.onclick=()=>{const pane=$('contextResult').querySelector(`[data-pane="${b.dataset.drawer}"]`);if(b.dataset.drawer==='why'&&lv<2){showView('quiz');return}pane.classList.toggle('show')});$('contextResult').querySelector('[data-ask-context]').onclick=()=>{showView('search');$('searchInput').value=`${p.label} 프로젝트에서 ${phase==='잘 모르겠습니다'?'현재 단계':phase}에 ${task} 업무를 하고 있어. 누구에게 먼저 뭐라고 물어보면 돼?`;runSearch()};window.CC_RUNTIME.renderContext();if(navigate!==false)showView('context')}
function isAsk(q){return /(누구|물어|문의|담당자|어디에\s*(?:물어|문의)|확인받|질문할|질의할|뭐라고\s*물어)/i.test(q)}function isTerm(q){return /(무슨\s*뜻|뜻이|뭐야|무엇이야|용어|정의|의미)/i.test(q)&&!/(하래|시키|업무|작성|수정|검토|찾아보)/i.test(q)}
function askRoute(q){if(/보고서|보고자료|협의자료|발주처|자료\s*(구성|내용|정리|작성)/i.test(q))return['보고서·협의자료 구성 → 선임 / 책임 / PM에게 먼저','보고자료의 목적, 메시지, 발주처에 보여줄 범위는 프로젝트 맥락을 아는 사내 상급자가 먼저 판단하는 영역입니다.','“이번 자료에서 발주처가 결정해야 하는 핵심이 무엇인지, 기준으로 볼 기존 자료가 무엇인지 확인 부탁드립니다.”'];if(/기둥|구조|슬래브|내력벽|철근|보\s*(위치|크기|춤|단면)/i.test(q))return['구조 관련 변경·검토 → 구조설계 협력업체','구조체 변경은 구조 안전성과 다른 분야 간섭에 직접 영향을 줍니다.','“현재 이 부분의 변경을 검토 중입니다. 구조 검토 범위와 같이 보내야 할 도면·조건이 무엇인지 확인 부탁드립니다.”'];if(/소방|스프링클러|제연|방재|헤드/i.test(q))return['소방 내용 → 소방설계 협력업체, 행정 적용은 관할 소방관서','기술 검토와 행정 적용 판단의 역할을 나눠서 확인하는 게 좋습니다.','“이 조건의 기술 검토가 필요한 범위와 관할 협의가 필요한 쟁점을 나눠서 확인 부탁드립니다.”'];if(/지구단위|도시계획|용도지역|용도지구|용도구역/i.test(q))return['도시계획 해석 → 사내 검토 후 관할 도시계획 담당','결정도서 해석은 먼저 사내에서 프로젝트 조건과 함께 검토하고 행정해석이 필요한 부분만 관할 부서에 확인합니다.','“최신 결정도서의 이 조항을 우리 대지에 이렇게 해석했는데, 적용 방향이 맞는지 확인 부탁드립니다.”'];if(/건축허가|인허가|변경허가|변경신고|착공신고|사용승인|사업계획/i.test(q))return['인허가 판단 → 사내 인허가 담당 / PM부터','먼저 기존 승인 경로와 변경 내용을 사내에서 정리한 뒤 공식 판단이 필요한 쟁점만 관할기관에 확인합니다.','“기존 승인도서 기준으로 이번 변경이 어느 절차에 영향을 주는지 먼저 확인 부탁드립니다.”'];if(/기계|전기|설비|배관|덕트|전력|냉각|통신|공조/i.test(q))return['기술설계 내용 → 해당 분야 협력업체 + 사내 담당자','전문 기술기준과 실제 설계값은 해당 분야가 검토하고 건축과의 우선순위·공간 조정은 사내 담당자가 함께 판단합니다.','“최신 건축도면 기준으로 이 구간의 필요 공간과 설계조건을 확인 부탁드립니다.”'];return['업무 판단이 막힘 → 선임 / 책임에게 먼저','질문의 분야가 아직 명확하지 않을 때는 바로 협력업체나 관할기관으로 보내기보다 프로젝트 맥락을 아는 사내 상급자에게 먼저 방향을 확인하는 게 좋습니다.','“현재 제가 판단이 안 되는 부분은 ○○입니다. 먼저 볼 기준자료와 다음에 누구와 협의하면 되는지 알려주실 수 있을까요?”']}
function taskRoute(q){const r=TASK_ROUTES.find(([re])=>re.test(q));return r?r[1]:{title:'상사가 시킨 일을 목적 → 필요한 자료 → 다음 행동으로 풀어보세요',meaning:'지시 문장만 보면 막막할 수 있으니 결과물의 목적과 누가 확인하는 자료인지부터 파악합니다.',first:'최종 결과물이 무엇인지, 언제까지인지, 참고할 기존 자료가 있는지 세 가지를 먼저 확인합니다.',where:'업무지시 · 기존 프로젝트 자료 · 최신 도면/모델',ask:'선임/책임에게 제가 이해한 업무 목적이 맞는지와 먼저 볼 기준자료가 무엇인지 확인하고 시작하세요.'}}
function termRoute(q){const key=Object.keys(TERMS).find(k=>norm(q).includes(norm(k)))||q.replace(/(뭐야|무슨뜻|뜻이야|뜻)$/g,'').trim();const d=TERMS[key];return d?{key,desc:d[0],next:d[1]}:{key:key||'검색 결과',desc:'현재 내장된 용어 데이터에 아직 없는 항목입니다.',next:'정확한 법적 의미가 필요한 경우 국가법령정보센터와 프로젝트 담당자에게 확인하세요.'}}
function runSearch(){return window.CC_RUNTIME.search($('searchInput').value)}

function renderQuizOverview(){return window.CC_QUIZ_UI.overview()}
function renderLevel(){const lv=viewLevel();if(lv===5){$('levelContent').innerHTML=`<div class="master-level-card"><div class="crown">👑✨</div><div class="kicker" style="color:#9B751D">PROJECT CONTEXT · LEGENDARY CLASS</div><h2>건 축 마 스 터</h2><div style="font-size:11px;font-weight:1000;letter-spacing:.16em;color:#B07C19">LV.MAX · ARCHITECTURE MASTER</div><p class="lead" style="margin:12px auto;max-width:620px">축하합니다. 이제 적어도 “누구한테 물어봐야 하지?”는 압니다.<br>모르면 검색 · 애매하면 확인 · 혼자 단정 금지.</p><div class="stamps"><span>WHAT ✓</span><span>WHY / WHERE ✓</span><span>HOW ✓</span><span>JUDGEMENT ✓</span></div><div class="master-actions"><button class="bling" id="replayMaster">🎺 마스터 입장 연출 다시보기</button><button data-view="home">아무렇지 않은 척 홈으로</button></div></div>`;$('replayMaster').onclick=showMaster;return}$('levelContent').innerHTML=`<div class="page-card level-card"><div class="kicker">CURRENT LEVEL</div><h2>LV.${lv} · ${LEVELS[lv].name}</h2><p class="lead">${LEVELS[lv].sub} 단계입니다. 레벨이 올라가도 홈 화면의 입구는 늘어나지 않고 같은 정보가 더 깊게 열립니다.</p><div class="level-grid">${[1,2,3,4].map(n=>`<div class="level-step ${n===lv?'on':''}"><b>LV.${n} · ${LEVELS[n].name}</b><span>${LEVELS[n].sub}</span></div>`).join('')}</div><div style="margin-top:16px"><button class="primary" data-view="quiz">승급 퀴즈 보기 →</button></div></div>`}
function confetti(){document.querySelector('.confetti')?.remove();const layer=document.createElement('div');layer.className='confetti';const c=['#F3B82F','#7657D4','#4C6FFF','#E77373','#38A984','#FFDA68'];for(let i=0;i<46;i++){const p=document.createElement('i');p.style.cssText=`--x:${i*37%101}%;--d:${2.6+(i%9)*.17}s;--delay:${(i%11)*.045}s;--drift:${(i%2?1:-1)*(20+(i%7)*6)}px;--c:${c[i%c.length]}`;layer.append(p)}document.body.append(layer);setTimeout(()=>layer.remove(),5000)}function showMaster(){if(viewLevel()!==5)return;$('masterOverlay').classList.add('show');confetti()}function hideMaster(){$('masterOverlay').classList.remove('show');document.querySelector('.confetti')?.remove()}
$('closeMaster').onclick=hideMaster;$('masterOverlay').onclick=e=>{if(e.target===$('masterOverlay'))hideMaster()};$('detailsToggle').onclick=()=>$('details').classList.toggle('show');$('analyze').onclick=analyze;document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{$('task').value=b.dataset.task;$('analyze').click()});
populate();updateMasterUI();renderQuizOverview();renderLevel();showView('home');
